from typing import Any, Protocol


class TaskRepository(Protocol):
    def create(self, task: dict[str, Any]) -> dict[str, Any]: ...
    def get(self, task_id: str) -> dict[str, Any] | None: ...
    def list_tasks(self, limit: int = 100) -> list[dict[str, Any]]: ...
    def update(self, task_id: str, patch: dict[str, Any]) -> dict[str, Any] | None: ...
    def claim_for_run(self, task_id: str) -> tuple[str, dict[str, Any] | None]: ...


class LogRepository(Protocol):
    def append(self, channel: str, entry: dict[str, Any]) -> None: ...
    def list_recent(self, channel: str, limit: int = 200) -> list[dict[str, Any]]: ...
